# Generated by Django 3.1 on 2021-02-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='image',
            field=models.ImageField(blank=True, upload_to='standard'),
        ),
    ]
